name: CI

on: [ push ]

jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: docker build -t sahtivahti/beer-calculator .
